# Site settings
title: Digital Exprt
subtitle: Putting Soft Back Into Software
email: alexbunardzic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  How to bring 'soft' back into software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alexbunardzic.github.io" # the base hostname & protocol for your site
name: Alex Bunardzic
twitter_username: alexbunardzic
github_username:  alexbunardzic

# Build settings
markdown: kramdown
